version: '3'
services:
  redis:
    image: "redis"
    ports:
      - "7379:6379"
  mongo:
    image: "mongo"
    ports:
      - "27018:27017"
    volumes:
      - "data:/data/db"
    user: mongodb
  bot:
    build: .
    ports:
     - "8444:8443"
    depends_on:
      - mongo
      - redis
    env_file: 
      - ./env/dev/bot
    volumes:
      - "./src:/opt/scrobblerbot/src"
volumes:
  data: